// <auto-generated />
using System;
using CollegeAcadimcManagementSystem.EF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollegeAcadimcManagementSystem.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250511141627_Iniail")]
    partial class Iniail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Mathematics 101"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Physics 101"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Chemistry 101"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Biology 101"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Computer Science 101"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "History 101"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Philosophy 101"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Economics 101"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Statistics 101"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Literature 101"
                        });
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.CourseInstructorAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("OfferedCourseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("OfferedCourseId");

                    b.ToTable("CourseInstructorAssignments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InstructorId = 1,
                            OfferedCourseId = 1
                        },
                        new
                        {
                            Id = 2,
                            InstructorId = 2,
                            OfferedCourseId = 2
                        },
                        new
                        {
                            Id = 3,
                            InstructorId = 3,
                            OfferedCourseId = 3
                        },
                        new
                        {
                            Id = 4,
                            InstructorId = 4,
                            OfferedCourseId = 4
                        },
                        new
                        {
                            Id = 5,
                            InstructorId = 5,
                            OfferedCourseId = 5
                        },
                        new
                        {
                            Id = 6,
                            InstructorId = 6,
                            OfferedCourseId = 6
                        },
                        new
                        {
                            Id = 7,
                            InstructorId = 7,
                            OfferedCourseId = 7
                        },
                        new
                        {
                            Id = 8,
                            InstructorId = 8,
                            OfferedCourseId = 8
                        },
                        new
                        {
                            Id = 9,
                            InstructorId = 9,
                            OfferedCourseId = 9
                        },
                        new
                        {
                            Id = 10,
                            InstructorId = 10,
                            OfferedCourseId = 10
                        },
                        new
                        {
                            Id = 11,
                            InstructorId = 11,
                            OfferedCourseId = 1
                        },
                        new
                        {
                            Id = 12,
                            InstructorId = 12,
                            OfferedCourseId = 2
                        },
                        new
                        {
                            Id = 13,
                            InstructorId = 13,
                            OfferedCourseId = 3
                        },
                        new
                        {
                            Id = 14,
                            InstructorId = 14,
                            OfferedCourseId = 4
                        },
                        new
                        {
                            Id = 15,
                            InstructorId = 15,
                            OfferedCourseId = 5
                        },
                        new
                        {
                            Id = 16,
                            InstructorId = 16,
                            OfferedCourseId = 6
                        },
                        new
                        {
                            Id = 17,
                            InstructorId = 17,
                            OfferedCourseId = 7
                        },
                        new
                        {
                            Id = 18,
                            InstructorId = 18,
                            OfferedCourseId = 8
                        },
                        new
                        {
                            Id = 19,
                            InstructorId = 19,
                            OfferedCourseId = 9
                        },
                        new
                        {
                            Id = 20,
                            InstructorId = 20,
                            OfferedCourseId = 10
                        });
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Department of Computer Science",
                            IsDeleted = false,
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Department of Mathematics",
                            IsDeleted = false,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Department of Physics",
                            IsDeleted = false,
                            Name = "Physics"
                        });
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.DepartmentStudyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("StudyLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StudyLevelId");

                    b.ToTable("DepartmentStudyLevels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            StudyLevelId = 1
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            StudyLevelId = 2
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            StudyLevelId = 3
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            StudyLevelId = 4
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            StudyLevelId = 5
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            StudyLevelId = 6
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 2,
                            StudyLevelId = 1
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 2,
                            StudyLevelId = 2
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 2,
                            StudyLevelId = 3
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 3,
                            StudyLevelId = 4
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 3,
                            StudyLevelId = 5
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 3,
                            StudyLevelId = 6
                        });
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Instructors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed@example.com",
                            FirstName = "أحمد محمد",
                            IsDeleted = false,
                            LastName = "محمد",
                            PhoneNumber = "1121456789"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@example.com",
                            FirstName = "سارة ",
                            IsDeleted = false,
                            LastName = "سارة علي",
                            PhoneNumber = "2927654321"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mohamed@example.com",
                            FirstName = "محمد حسن",
                            IsDeleted = false,
                            LastName = "محمد حسن",
                            PhoneNumber = "31128833445"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "leila@example.com",
                            FirstName = "ليلى إبراهيم",
                            IsDeleted = false,
                            LastName = "ليلى إبراهيم",
                            PhoneNumber = "4243344556"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali@example.com",
                            FirstName = "علي يوسف",
                            IsDeleted = false,
                            LastName = "علي يوسف",
                            PhoneNumber = "0344455667"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatima@example.com",
                            FirstName = "فاطمة سعيد",
                            IsDeleted = false,
                            LastName = "فاطمة سعيد",
                            PhoneNumber = "5445566778"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khaled@example.com",
                            FirstName = "خالد عبد الله",
                            IsDeleted = false,
                            LastName = "خالد عبد الله",
                            PhoneNumber = "6556677889"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariam@example.com",
                            FirstName = "مريم أحمد",
                            IsDeleted = false,
                            LastName = "مريم أحمد",
                            PhoneNumber = "7667788990"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssef@example.com",
                            FirstName = "يوسف علي",
                            IsDeleted = false,
                            LastName = "يوسف علي",
                            PhoneNumber = "0878899001"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nora@example.com",
                            FirstName = "نورا محمد",
                            IsDeleted = false,
                            LastName = "نورا محمد",
                            PhoneNumber = "9889900112"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hassan@example.com",
                            FirstName = "حسن علي",
                            IsDeleted = false,
                            LastName = "حسن علي",
                            PhoneNumber = "14490011223"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mona@example.com",
                            FirstName = "منى سعيد",
                            IsDeleted = false,
                            LastName = "منى سعيد",
                            PhoneNumber = "01022122334"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar@example.com",
                            FirstName = "عمر خالد",
                            IsDeleted = false,
                            LastName = "عمر خالد",
                            PhoneNumber = "01112233445"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "huda@example.com",
                            FirstName = "هدى إبراهيم",
                            IsDeleted = false,
                            LastName = "هدى إبراهيم",
                            PhoneNumber = "2223344556"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yasser@example.com",
                            FirstName = "ياسر يوسف",
                            IsDeleted = false,
                            LastName = "ياسر يوسف",
                            PhoneNumber = "03744455667"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nadia@example.com",
                            FirstName = "نادية سعيد",
                            IsDeleted = false,
                            LastName = "نادية سعيد",
                            PhoneNumber = "0045566778"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "majed@example.com",
                            FirstName = "ماجد عبد الله",
                            IsDeleted = false,
                            LastName = "ماجد عبد الله",
                            PhoneNumber = "9956677889"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "salma@example.com",
                            FirstName = "سلمى أحمد",
                            IsDeleted = false,
                            LastName = "سلمى أحمد",
                            PhoneNumber = "0667788990"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ziad@example.com",
                            FirstName = "زياد علي",
                            IsDeleted = false,
                            LastName = "زياد علي",
                            PhoneNumber = "0228899001"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noor@example.com",
                            FirstName = "نور محمد",
                            IsDeleted = false,
                            LastName = "نور محمد",
                            PhoneNumber = "0874900112"
                        });
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.OfferedCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentStudyLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepartmentStudyLevelId");

                    b.ToTable("OfferedCourses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            DepartmentStudyLevelId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            DepartmentStudyLevelId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            DepartmentStudyLevelId = 2
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            DepartmentStudyLevelId = 2
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            DepartmentStudyLevelId = 3
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 6,
                            DepartmentStudyLevelId = 3
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 7,
                            DepartmentStudyLevelId = 4
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 8,
                            DepartmentStudyLevelId = 4
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 9,
                            DepartmentStudyLevelId = 5
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 10,
                            DepartmentStudyLevelId = 5
                        });
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed@example.com",
                            FirstName = "أحمد محمد",
                            IsDeleted = false,
                            LastName = "محمد",
                            PhoneNumber = "1121456789"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@example.com",
                            FirstName = "سارة ",
                            IsDeleted = false,
                            LastName = "سارة علي",
                            PhoneNumber = "2927654321"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mohamed@example.com",
                            FirstName = "محمد حسن",
                            IsDeleted = false,
                            LastName = "محمد حسن",
                            PhoneNumber = "31128833445"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "leila@example.com",
                            FirstName = "ليلى إبراهيم",
                            IsDeleted = false,
                            LastName = "ليلى إبراهيم",
                            PhoneNumber = "4243344556"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali@example.com",
                            FirstName = "علي يوسف",
                            IsDeleted = false,
                            LastName = "علي يوسف",
                            PhoneNumber = "0344455667"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatima@example.com",
                            FirstName = "فاطمة سعيد",
                            IsDeleted = false,
                            LastName = "فاطمة سعيد",
                            PhoneNumber = "5445566778"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khaled@example.com",
                            FirstName = "خالد عبد الله",
                            IsDeleted = false,
                            LastName = "خالد عبد الله",
                            PhoneNumber = "6556677889"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariam@example.com",
                            FirstName = "مريم أحمد",
                            IsDeleted = false,
                            LastName = "مريم أحمد",
                            PhoneNumber = "7667788990"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssef@example.com",
                            FirstName = "يوسف علي",
                            IsDeleted = false,
                            LastName = "يوسف علي",
                            PhoneNumber = "0878899001"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nora@example.com",
                            FirstName = "نورا محمد",
                            IsDeleted = false,
                            LastName = "نورا محمد",
                            PhoneNumber = "9889900112"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hassan@example.com",
                            FirstName = "حسن علي",
                            IsDeleted = false,
                            LastName = "حسن علي",
                            PhoneNumber = "14490011223"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mona@example.com",
                            FirstName = "منى سعيد",
                            IsDeleted = false,
                            LastName = "منى سعيد",
                            PhoneNumber = "01022122334"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar@example.com",
                            FirstName = "عمر خالد",
                            IsDeleted = false,
                            LastName = "عمر خالد",
                            PhoneNumber = "01112233445"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "huda@example.com",
                            FirstName = "هدى إبراهيم",
                            IsDeleted = false,
                            LastName = "هدى إبراهيم",
                            PhoneNumber = "2223344556"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yasser@example.com",
                            FirstName = "ياسر يوسف",
                            IsDeleted = false,
                            LastName = "ياسر يوسف",
                            PhoneNumber = "03744455667"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nadia@example.com",
                            FirstName = "نادية سعيد",
                            IsDeleted = false,
                            LastName = "نادية سعيد",
                            PhoneNumber = "0045566778"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "majed@example.com",
                            FirstName = "ماجد عبد الله",
                            IsDeleted = false,
                            LastName = "ماجد عبد الله",
                            PhoneNumber = "9956677889"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "salma@example.com",
                            FirstName = "سلمى أحمد",
                            IsDeleted = false,
                            LastName = "سلمى أحمد",
                            PhoneNumber = "0667788990"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ziad@example.com",
                            FirstName = "زياد علي",
                            IsDeleted = false,
                            LastName = "زياد علي",
                            PhoneNumber = "0228899001"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noor@example.com",
                            FirstName = "نور محمد",
                            IsDeleted = false,
                            LastName = "نور محمد",
                            PhoneNumber = "0874900112"
                        });
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.StudentEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<float>("Grade")
                        .HasColumnType("real");

                    b.Property<int>("OfferedCourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfferedCourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentEnrollments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2023, 10, 1),
                            Grade = 85.5f,
                            OfferedCourseId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2023, 10, 2),
                            Grade = 90f,
                            OfferedCourseId = 2,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2023, 10, 3),
                            Grade = 78f,
                            OfferedCourseId = 3,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2023, 10, 4),
                            Grade = 88f,
                            OfferedCourseId = 4,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2023, 10, 5),
                            Grade = 92f,
                            OfferedCourseId = 5,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2023, 10, 6),
                            Grade = 80f,
                            OfferedCourseId = 6,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2023, 10, 7),
                            Grade = 75f,
                            OfferedCourseId = 7,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2023, 10, 8),
                            Grade = 89f,
                            OfferedCourseId = 8,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2023, 10, 9),
                            Grade = 95f,
                            OfferedCourseId = 9,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2023, 10, 10),
                            Grade = 85f,
                            OfferedCourseId = 10,
                            StudentId = 10
                        });
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.StudyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StudyLevels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Level 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Level 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Level 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Level 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Level 5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Level 6"
                        });
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.CourseInstructorAssignment", b =>
                {
                    b.HasOne("CollegeAcadimcManagementSystem.Core.Entites.Instructor", "Instructor")
                        .WithMany("CourseInstructorAssignments")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeAcadimcManagementSystem.Core.Entites.OfferedCourse", "OfferedCourse")
                        .WithMany("CourseInstructorAssignments")
                        .HasForeignKey("OfferedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("OfferedCourse");
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.DepartmentStudyLevel", b =>
                {
                    b.HasOne("CollegeAcadimcManagementSystem.Core.Entites.Department", "Department")
                        .WithMany("DepartmentStudyLevels")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeAcadimcManagementSystem.Core.Entites.StudyLevel", "StudyLevel")
                        .WithMany("DepartmentStudyLevels")
                        .HasForeignKey("StudyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("StudyLevel");
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.OfferedCourse", b =>
                {
                    b.HasOne("CollegeAcadimcManagementSystem.Core.Entites.Course", "Course")
                        .WithMany("OfferedCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeAcadimcManagementSystem.Core.Entites.DepartmentStudyLevel", "DepartmentStudyLevel")
                        .WithMany("OfferedCourses")
                        .HasForeignKey("DepartmentStudyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("DepartmentStudyLevel");
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.StudentEnrollment", b =>
                {
                    b.HasOne("CollegeAcadimcManagementSystem.Core.Entites.OfferedCourse", "OfferedCourses")
                        .WithMany("StudentEnrollments")
                        .HasForeignKey("OfferedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeAcadimcManagementSystem.Core.Entites.Student", "Student")
                        .WithMany("StudentEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfferedCourses");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.Course", b =>
                {
                    b.Navigation("OfferedCourses");
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.Department", b =>
                {
                    b.Navigation("DepartmentStudyLevels");
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.DepartmentStudyLevel", b =>
                {
                    b.Navigation("OfferedCourses");
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.Instructor", b =>
                {
                    b.Navigation("CourseInstructorAssignments");
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.OfferedCourse", b =>
                {
                    b.Navigation("CourseInstructorAssignments");

                    b.Navigation("StudentEnrollments");
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.Student", b =>
                {
                    b.Navigation("StudentEnrollments");
                });

            modelBuilder.Entity("CollegeAcadimcManagementSystem.Core.Entites.StudyLevel", b =>
                {
                    b.Navigation("DepartmentStudyLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
