global using CollegeAcadimcManagementSystem.Core.DTOs;
global using CollegeAcadimcManagementSystem.Core.Entites;
global using CollegeAcadimcManagementSystem.Core.Interfaces;
global using CollegeAcadimcManagementSystem.Core.Models.Response;
global using Microsoft.Extensions.DependencyInjection;
global using System.ComponentModel.DataAnnotations;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Text.Json.Serialization;
